"use client";
import { create } from "zustand";
import { backgroundMusicAsset, soundAssets, type SoundEvent } from "@/config/sounds";
const STORAGE_KEY="circzles.audio.v1", pools=new Map<string,Set<HTMLAudioElement>>(), lastPlayed=new Map<SoundEvent,number>(); let music:HTMLAudioElement|undefined,preferencesHydrated=false,audioUnlocked=false,duckMultiplier=1,duckTimer:number|undefined;
interface SoundPreferences{master:boolean;effects:boolean;music:boolean;notifications:boolean;reducedMotion:boolean;effectsVolume:number;musicVolume:number} interface PlayOptions{playbackRate?:number;volume?:number} interface SoundState extends SoundPreferences{setSound:(patch:Partial<SoundPreferences>)=>void;play:(name:SoundEvent,options?:PlayOptions)=>void}
const defaults:SoundPreferences={master:true,effects:true,music:true,notifications:true,reducedMotion:false,effectsVolume:.4,musicVolume:.1};
export const useSound=create<SoundState>((set,get)=>({...defaults,setSound:(patch)=>{set(patch);const next={...get(),...patch};persistPreferences(next);syncMusic(next)},play:(name,options)=>{if(typeof window==="undefined")return;const state=get(),asset=soundAssets[name],now=performance.now();if(!state.master||!asset.path||(asset.category==="effect"&&!state.effects)||(asset.category==="notification"&&!state.notifications))return;if(asset.cooldownMs&&now-(lastPlayed.get(name)??-Infinity)<asset.cooldownMs)return;lastPlayed.set(name,now);try{const active=pools.get(asset.path)??new Set<HTMLAudioElement>();pools.set(asset.path,active);if(active.size>=(asset.maxPolyphony??4))return;const audio=new Audio(asset.path);active.add(audio);audio.volume=clamp(state.effectsVolume*(asset.volume??1)*(options?.volume??1));audio.playbackRate=options?.playbackRate??asset.playbackRate??1;audio.currentTime=(asset.startAtMs??0)/1000;let timer:number|undefined;const release=()=>{if(timer)clearTimeout(timer);active.delete(audio);audio.removeEventListener("ended",release);audio.removeEventListener("error",release)};audio.addEventListener("ended",release);audio.addEventListener("error",release);if(asset.stopAfterMs)timer=window.setTimeout(()=>{audio.pause();release()},asset.stopAfterMs);void audio.play().catch(release)}catch{/* optional audio */}}}));
export function hydrateAudioPreferences(){if(typeof window==="undefined"||preferencesHydrated)return;preferencesHydrated=true;try{useSound.setState({...defaults,...JSON.parse(localStorage.getItem(STORAGE_KEY)??"{}")})}catch{useSound.setState(defaults)}}
export function armBackgroundMusic(){if(typeof window==="undefined")return()=>undefined;const start=()=>{audioUnlocked=true;syncMusic(useSound.getState())};window.addEventListener("pointerdown",start,{once:true});window.addEventListener("keydown",start,{once:true});return()=>{window.removeEventListener("pointerdown",start);window.removeEventListener("keydown",start)}}
export function resumeBackgroundMusic(){audioUnlocked=true;syncMusic(useSound.getState())} export function pauseBackgroundMusic(){music?.pause()} export function duckMusic(durationMs=1800){duckMultiplier=.38;syncMusicVolume();if(duckTimer)clearTimeout(duckTimer);duckTimer=window.setTimeout(()=>{duckMultiplier=1;syncMusicVolume()},durationMs)}
function syncMusic(state:SoundPreferences){if(typeof window==="undefined")return;music??=new Audio(backgroundMusicAsset);music.loop=true;syncMusicVolume(state);if(audioUnlocked&&state.master&&state.music)void music.play().catch(()=>undefined);else music.pause()} function syncMusicVolume(state:SoundPreferences=useSound.getState()){if(music)music.volume=clamp(state.musicVolume*duckMultiplier)} function persistPreferences(state:SoundPreferences){if(!preferencesHydrated)return;const{master,effects,music:musicEnabled,notifications,reducedMotion,effectsVolume,musicVolume}=state;localStorage.setItem(STORAGE_KEY,JSON.stringify({master,effects,music:musicEnabled,notifications,reducedMotion,effectsVolume,musicVolume}))} function clamp(v:number){return Math.max(0,Math.min(1,v))}
export function playSound(name:SoundEvent,options?:PlayOptions){try{useSound.getState().play(name,options)}catch{/* optional feedback */}}
